---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash.
  yum: pkg=logstash state=installed


- name: Fix java8 in defualt settings
  lineinfile:
    dest: "/etc/default/logstash"
    regexp: 'JAVACMD="/usr/bin/java"'
    line: 'JAVACMD="/usr/bin/java8"'
  notify:
    - restart logstash



