---
- name: Stop Kibana service
  become: yes
  service:
    name: kibana
    state: stopped
  ignore_errors: true

- name: "Download and unpack {{ kibana.tarball }}"
  become: yes
  get_url:
    url: "{{ kibana.download_base_url }}{{ kibana.tarball }}.tar.gz"
    dest: "/usr/local/src/{{ kibana.tarball }}.tar.gz"

- name: Extract the Kibana tarball
  become: yes
  unarchive:
    src: "/usr/local/src/{{ kibana.tarball }}.tar.gz"
    dest: "/usr/local/src/"
    copy: no
    creates: "/usr/local/src/{{ kibana.tarball }}"

- name: Install Kibana
  become: yes
  command: "cp -R /usr/local/src/{{ kibana.tarball }} {{ kibana.install_dir }}"
  args:
    creates: "{{ kibana.install_dir }}"
    removes: "/usr/local/src/{{ kibana.tarball }}"

- name: Remove Kibana plugins
  become: yes
  command: "{{ kibana.install_dir }}/bin/kibana-plugin remove {{ item.plugin_name }}"
  args:
    chdir: "{{ kibana.install_dir }}"
    creates: "{{ kibana.install_dir }}/installedPlugins/{{ item.plugin_dir }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ kibana.plugins }}"
  ignore_errors: true

- name: Install Kibana plugins
  become: yes
  command: "{{ kibana.install_dir }}/bin/kibana-plugin install {{ item.plugin_name }}"
  args:
    chdir: "{{ kibana.install_dir }}"
    creates: "{{ kibana.install_dir }}/installedPlugins/{{ item.plugin_dir }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ kibana.plugins }}"

- name: Ensure Systemd Service Configuraiton
  become: yes
  template:
    src: kibana.service.j2
    dest: /etc/systemd/system/kibana.service
    mode: 764
  notify:
    - start kibana
  when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: Install Kibana service
  become: yes
  template:
    src: service.conf.j2
    dest: /etc/init/kibana.conf
    mode: 764
  notify:
    - start kibana
  when: ansible_service_mgr is not defined or ansible_service_mgr != 'systemd'

- name: Enable Kibana service
  become: yes
  service:
    name: kibana
    enabled: yes
    daemon_reload: yes
  notify:
    - start kibana
