---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Stop filebeat if started
  service: name=filebeat state=stopped
  ignore_errors: yes

- name: Uninstall Filebeat.
  package: name=filebeat state=absent

- name: Install Filebeat.
  package: name=filebeat state=present

- include: config.yml
  when: filebeat_create_config

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: restarted
    enabled: yes
